version: '3.8'

services:
  # NestJS Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3030:3030"
    env_file:
      - .env  # Load environment variables from .env file