version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trade_me_bot
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - WEBSOCKET_URL=${WEBSOCKET_URL}
      - API_URL=${API_URL}
    volumes:
      - ./logs:/app/logs
